/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Binding</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.ExternalBinding#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getExternalBinding()
 * @model
 * @generated
 */
public interface ExternalBinding extends Expression, Binding
{
  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference.
   * @see #setParams(ParameterUse)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getExternalBinding_Params()
   * @model containment="true"
   * @generated
   */
  ParameterUse getParams();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.ExternalBinding#getParams <em>Params</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Params</em>' containment reference.
   * @see #getParams()
   * @generated
   */
  void setParams(ParameterUse value);

} // ExternalBinding
